/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 28
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 24
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 2
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_content_token1 = 1,
  anon_sym_LBRACE_LBRACE = 2,
  anon_sym_LBRACE_LBRACE_DASH = 3,
  anon_sym_RBRACE_RBRACE = 4,
  anon_sym_DASH_RBRACE_RBRACE = 5,
  anon_sym_DASH_DASH_DASH = 6,
  anon_sym_PIPE_GT = 7,
  sym_keyword = 8,
  aux_sym_code_snippet_token1 = 9,
  sym_close_keyword = 10,
  sym_comment = 11,
  sym__code = 12,
  sym__front_matter_content = 13,
  sym_template = 14,
  sym_content = 15,
  sym_tag = 16,
  sym_front_matter = 17,
  sym__expression = 18,
  sym_filter = 19,
  sym_code_snippet = 20,
  aux_sym_template_repeat1 = 21,
  aux_sym_content_repeat1 = 22,
  aux_sym_filter_repeat1 = 23,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_content_token1] = "content_token1",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_LBRACE_LBRACE_DASH] = "{{-",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_DASH_RBRACE_RBRACE] = "-}}",
  [anon_sym_DASH_DASH_DASH] = "---",
  [anon_sym_PIPE_GT] = "|>",
  [sym_keyword] = "keyword",
  [aux_sym_code_snippet_token1] = "code_snippet_token1",
  [sym_close_keyword] = "keyword",
  [sym_comment] = "comment",
  [sym__code] = "_code",
  [sym__front_matter_content] = "front_matter_content",
  [sym_template] = "template",
  [sym_content] = "content",
  [sym_tag] = "tag",
  [sym_front_matter] = "front_matter",
  [sym__expression] = "_expression",
  [sym_filter] = "filter",
  [sym_code_snippet] = "code",
  [aux_sym_template_repeat1] = "template_repeat1",
  [aux_sym_content_repeat1] = "content_repeat1",
  [aux_sym_filter_repeat1] = "filter_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_content_token1] = aux_sym_content_token1,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_LBRACE_LBRACE_DASH] = anon_sym_LBRACE_LBRACE_DASH,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_DASH_RBRACE_RBRACE] = anon_sym_DASH_RBRACE_RBRACE,
  [anon_sym_DASH_DASH_DASH] = anon_sym_DASH_DASH_DASH,
  [anon_sym_PIPE_GT] = anon_sym_PIPE_GT,
  [sym_keyword] = sym_keyword,
  [aux_sym_code_snippet_token1] = aux_sym_code_snippet_token1,
  [sym_close_keyword] = sym_keyword,
  [sym_comment] = sym_comment,
  [sym__code] = sym__code,
  [sym__front_matter_content] = sym__front_matter_content,
  [sym_template] = sym_template,
  [sym_content] = sym_content,
  [sym_tag] = sym_tag,
  [sym_front_matter] = sym_front_matter,
  [sym__expression] = sym__expression,
  [sym_filter] = sym_filter,
  [sym_code_snippet] = sym_code_snippet,
  [aux_sym_template_repeat1] = aux_sym_template_repeat1,
  [aux_sym_content_repeat1] = aux_sym_content_repeat1,
  [aux_sym_filter_repeat1] = aux_sym_filter_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_content_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_code_snippet_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_close_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__code] = {
    .visible = false,
    .named = true,
  },
  [sym__front_matter_content] = {
    .visible = true,
    .named = true,
  },
  [sym_template] = {
    .visible = true,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_front_matter] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_filter] = {
    .visible = true,
    .named = true,
  },
  [sym_code_snippet] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_template_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_filter_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = sym_code_snippet,
  },
  [2] = {
    [1] = sym_code_snippet,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(73);
      ADVANCE_MAP(
        '#', 70,
        '-', 2,
        '/', 13,
        'd', 90,
        'e', 89,
        'f', 94,
        'i', 93,
        'l', 88,
        'o', 92,
        's', 91,
        '{', 67,
        '|', 4,
        '}', 68,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (lookahead == '!' ||
          lookahead == '(' ||
          lookahead == ')' ||
          lookahead == '.' ||
          lookahead == '>' ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(96);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(3);
      if (lookahead == '}') ADVANCE(69);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(84);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(85);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(62);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(66);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(63);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(29);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(57);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(24);
      if (lookahead == 'x') ADVANCE(49);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(58);
      END_STATE();
    case 12:
      if (lookahead == 'c') ADVANCE(30);
      END_STATE();
    case 13:
      if (lookahead == 'd') ADVANCE(19);
      if (lookahead == 'e') ADVANCE(10);
      if (lookahead == 'f') ADVANCE(40);
      if (lookahead == 'i') ADVANCE(20);
      if (lookahead == 'l') ADVANCE(6);
      if (lookahead == 's') ADVANCE(18);
      END_STATE();
    case 14:
      if (lookahead == 'd') ADVANCE(16);
      END_STATE();
    case 15:
      if (lookahead == 'd') ADVANCE(17);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(86);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(95);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(56);
      if (lookahead == 'l') ADVANCE(42);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 20:
      if (lookahead == 'f') ADVANCE(95);
      if (lookahead == 'm') ADVANCE(49);
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 21:
      if (lookahead == 'f') ADVANCE(5);
      END_STATE();
    case 22:
      if (lookahead == 'f') ADVANCE(7);
      END_STATE();
    case 23:
      if (lookahead == 'h') ADVANCE(36);
      END_STATE();
    case 24:
      if (lookahead == 'h') ADVANCE(38);
      END_STATE();
    case 25:
      if (lookahead == 'i') ADVANCE(41);
      END_STATE();
    case 26:
      if (lookahead == 'i') ADVANCE(44);
      END_STATE();
    case 27:
      if (lookahead == 'l') ADVANCE(55);
      END_STATE();
    case 28:
      if (lookahead == 'l') ADVANCE(56);
      END_STATE();
    case 29:
      if (lookahead == 'l') ADVANCE(60);
      END_STATE();
    case 30:
      if (lookahead == 'l') ADVANCE(64);
      END_STATE();
    case 31:
      if (lookahead == 'm') ADVANCE(86);
      END_STATE();
    case 32:
      if (lookahead == 'n') ADVANCE(86);
      END_STATE();
    case 33:
      if (lookahead == 'n') ADVANCE(95);
      END_STATE();
    case 34:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 35:
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 36:
      if (lookahead == 'o') ADVANCE(86);
      END_STATE();
    case 37:
      if (lookahead == 'o') ADVANCE(55);
      END_STATE();
    case 38:
      if (lookahead == 'o') ADVANCE(95);
      END_STATE();
    case 39:
      if (lookahead == 'o') ADVANCE(31);
      END_STATE();
    case 40:
      if (lookahead == 'o') ADVANCE(52);
      if (lookahead == 'u') ADVANCE(35);
      END_STATE();
    case 41:
      if (lookahead == 'o') ADVANCE(32);
      END_STATE();
    case 42:
      if (lookahead == 'o') ADVANCE(56);
      END_STATE();
    case 43:
      if (lookahead == 'o') ADVANCE(51);
      END_STATE();
    case 44:
      if (lookahead == 'o') ADVANCE(33);
      END_STATE();
    case 45:
      if (lookahead == 'o') ADVANCE(59);
      END_STATE();
    case 46:
      if (lookahead == 'o') ADVANCE(53);
      END_STATE();
    case 47:
      if (lookahead == 'o') ADVANCE(61);
      END_STATE();
    case 48:
      if (lookahead == 'p') ADVANCE(43);
      END_STATE();
    case 49:
      if (lookahead == 'p') ADVANCE(46);
      END_STATE();
    case 50:
      if (lookahead == 'r') ADVANCE(86);
      END_STATE();
    case 51:
      if (lookahead == 'r') ADVANCE(55);
      END_STATE();
    case 52:
      if (lookahead == 'r') ADVANCE(95);
      END_STATE();
    case 53:
      if (lookahead == 'r') ADVANCE(56);
      END_STATE();
    case 54:
      if (lookahead == 's') ADVANCE(16);
      END_STATE();
    case 55:
      if (lookahead == 't') ADVANCE(86);
      END_STATE();
    case 56:
      if (lookahead == 't') ADVANCE(95);
      END_STATE();
    case 57:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 58:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 59:
      if (lookahead == 'u') ADVANCE(55);
      END_STATE();
    case 60:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 61:
      if (lookahead == 'u') ADVANCE(56);
      END_STATE();
    case 62:
      if (lookahead == 'u') ADVANCE(27);
      END_STATE();
    case 63:
      if (lookahead == 'u') ADVANCE(28);
      END_STATE();
    case 64:
      if (lookahead == 'u') ADVANCE(15);
      END_STATE();
    case 65:
      if (lookahead == 'y') ADVANCE(45);
      END_STATE();
    case 66:
      if (lookahead == 'y') ADVANCE(47);
      END_STATE();
    case 67:
      if (lookahead == '{') ADVANCE(80);
      END_STATE();
    case 68:
      if (lookahead == '}') ADVANCE(82);
      END_STATE();
    case 69:
      if (lookahead == '}') ADVANCE(83);
      END_STATE();
    case 70:
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(1);
      END_STATE();
    case 71:
      if (eof) ADVANCE(73);
      if (lookahead == '-') ADVANCE(76);
      if (lookahead == '{') ADVANCE(77);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(75);
      if (lookahead != 0) ADVANCE(79);
      END_STATE();
    case 72:
      if (eof) ADVANCE(73);
      if (lookahead == '{') ADVANCE(77);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(78);
      if (lookahead != 0) ADVANCE(79);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (lookahead == '-') ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(79);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (lookahead == '-') ADVANCE(76);
      if (lookahead == '{') ADVANCE(77);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(75);
      if (lookahead != 0) ADVANCE(79);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (lookahead == '-') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(79);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (lookahead == '{') ADVANCE(80);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (lookahead == '{') ADVANCE(77);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(78);
      if (lookahead != 0) ADVANCE(79);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(79);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      if (lookahead == '-') ADVANCE(81);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE_DASH);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_DASH_RBRACE_RBRACE);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_DASH);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_PIPE_GT);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_keyword);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_code_snippet_token1);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_code_snippet_token1);
      if (lookahead == 'a') ADVANCE(65);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_code_snippet_token1);
      if (lookahead == 'c') ADVANCE(23);
      if (lookahead == 'l') ADVANCE(54);
      if (lookahead == 'x') ADVANCE(48);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(aux_sym_code_snippet_token1);
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_code_snippet_token1);
      if (lookahead == 'e') ADVANCE(55);
      if (lookahead == 'l') ADVANCE(37);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_code_snippet_token1);
      if (lookahead == 'f') ADVANCE(86);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_code_snippet_token1);
      if (lookahead == 'f') ADVANCE(86);
      if (lookahead == 'm') ADVANCE(48);
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_code_snippet_token1);
      if (lookahead == 'o') ADVANCE(50);
      if (lookahead == 'r') ADVANCE(39);
      if (lookahead == 'u') ADVANCE(34);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_close_keyword);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 71},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 72},
  [4] = {.lex_state = 72},
  [5] = {.lex_state = 72},
  [6] = {.lex_state = 72},
  [7] = {.lex_state = 72},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 72},
  [10] = {.lex_state = 0, .external_lex_state = 2},
  [11] = {.lex_state = 72},
  [12] = {.lex_state = 72},
  [13] = {.lex_state = 72},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 72},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0, .external_lex_state = 2},
  [25] = {.lex_state = 0, .external_lex_state = 3},
  [26] = {.lex_state = 0, .external_lex_state = 2},
  [27] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE_DASH] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_DASH_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_DASH_DASH_DASH] = ACTIONS(1),
    [anon_sym_PIPE_GT] = ACTIONS(1),
    [sym_keyword] = ACTIONS(1),
    [aux_sym_code_snippet_token1] = ACTIONS(1),
    [sym_close_keyword] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym__code] = ACTIONS(1),
    [sym__front_matter_content] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_template] = STATE(23),
    [sym_content] = STATE(3),
    [sym_tag] = STATE(3),
    [sym_front_matter] = STATE(4),
    [aux_sym_template_repeat1] = STATE(3),
    [aux_sym_content_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_content_token1] = ACTIONS(5),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(7),
    [anon_sym_LBRACE_LBRACE_DASH] = ACTIONS(7),
    [anon_sym_DASH_DASH_DASH] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(13), 1,
      anon_sym_PIPE_GT,
    ACTIONS(15), 1,
      sym_keyword,
    ACTIONS(17), 1,
      aux_sym_code_snippet_token1,
    STATE(8), 1,
      sym__expression,
    STATE(14), 1,
      aux_sym_filter_repeat1,
    STATE(19), 1,
      sym_code_snippet,
    STATE(21), 1,
      sym_filter,
    ACTIONS(11), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
    ACTIONS(19), 2,
      sym_close_keyword,
      sym_comment,
  [30] = 5,
    ACTIONS(5), 1,
      aux_sym_content_token1,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    STATE(7), 1,
      aux_sym_content_repeat1,
    ACTIONS(7), 2,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
    STATE(5), 3,
      sym_content,
      sym_tag,
      aux_sym_template_repeat1,
  [49] = 5,
    ACTIONS(5), 1,
      aux_sym_content_token1,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    STATE(7), 1,
      aux_sym_content_repeat1,
    ACTIONS(7), 2,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
    STATE(6), 3,
      sym_content,
      sym_tag,
      aux_sym_template_repeat1,
  [68] = 5,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      aux_sym_content_token1,
    STATE(7), 1,
      aux_sym_content_repeat1,
    ACTIONS(28), 2,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
    STATE(5), 3,
      sym_content,
      sym_tag,
      aux_sym_template_repeat1,
  [87] = 5,
    ACTIONS(5), 1,
      aux_sym_content_token1,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    STATE(7), 1,
      aux_sym_content_repeat1,
    ACTIONS(7), 2,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
    STATE(5), 3,
      sym_content,
      sym_tag,
      aux_sym_template_repeat1,
  [106] = 4,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      aux_sym_content_token1,
    STATE(9), 1,
      aux_sym_content_repeat1,
    ACTIONS(37), 2,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
  [120] = 4,
    ACTIONS(13), 1,
      anon_sym_PIPE_GT,
    STATE(14), 1,
      aux_sym_filter_repeat1,
    STATE(22), 1,
      sym_filter,
    ACTIONS(39), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
  [134] = 4,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    ACTIONS(43), 1,
      aux_sym_content_token1,
    STATE(9), 1,
      aux_sym_content_repeat1,
    ACTIONS(46), 2,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
  [148] = 2,
    ACTIONS(50), 1,
      sym__code,
    ACTIONS(48), 3,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PIPE_GT,
  [157] = 2,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
    ACTIONS(54), 3,
      aux_sym_content_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
  [166] = 2,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    ACTIONS(58), 3,
      aux_sym_content_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
  [175] = 2,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
    ACTIONS(62), 3,
      aux_sym_content_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
  [184] = 3,
    ACTIONS(13), 1,
      anon_sym_PIPE_GT,
    STATE(15), 1,
      aux_sym_filter_repeat1,
    ACTIONS(64), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
  [195] = 3,
    ACTIONS(68), 1,
      anon_sym_PIPE_GT,
    STATE(15), 1,
      aux_sym_filter_repeat1,
    ACTIONS(66), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
  [206] = 2,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
    ACTIONS(73), 3,
      aux_sym_content_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_DASH,
  [215] = 1,
    ACTIONS(75), 3,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PIPE_GT,
  [221] = 1,
    ACTIONS(77), 3,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PIPE_GT,
  [227] = 1,
    ACTIONS(48), 3,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PIPE_GT,
  [233] = 1,
    ACTIONS(79), 3,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PIPE_GT,
  [239] = 1,
    ACTIONS(39), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
  [244] = 1,
    ACTIONS(81), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
  [249] = 1,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
  [253] = 1,
    ACTIONS(85), 1,
      sym__code,
  [257] = 1,
    ACTIONS(87), 1,
      sym__front_matter_content,
  [261] = 1,
    ACTIONS(89), 1,
      sym__code,
  [265] = 1,
    ACTIONS(91), 1,
      anon_sym_DASH_DASH_DASH,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 30,
  [SMALL_STATE(4)] = 49,
  [SMALL_STATE(5)] = 68,
  [SMALL_STATE(6)] = 87,
  [SMALL_STATE(7)] = 106,
  [SMALL_STATE(8)] = 120,
  [SMALL_STATE(9)] = 134,
  [SMALL_STATE(10)] = 148,
  [SMALL_STATE(11)] = 157,
  [SMALL_STATE(12)] = 166,
  [SMALL_STATE(13)] = 175,
  [SMALL_STATE(14)] = 184,
  [SMALL_STATE(15)] = 195,
  [SMALL_STATE(16)] = 206,
  [SMALL_STATE(17)] = 215,
  [SMALL_STATE(18)] = 221,
  [SMALL_STATE(19)] = 227,
  [SMALL_STATE(20)] = 233,
  [SMALL_STATE(21)] = 239,
  [SMALL_STATE(22)] = 244,
  [SMALL_STATE(23)] = 249,
  [SMALL_STATE(24)] = 253,
  [SMALL_STATE(25)] = 257,
  [SMALL_STATE(26)] = 261,
  [SMALL_STATE(27)] = 265,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 2, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 1),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 2, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 3, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 3, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_front_matter, 3, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_front_matter, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_filter, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_filter_repeat1, 2, 0, 0),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_filter_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 4, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 4, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_filter_repeat1, 2, 0, 2),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 2, 0, 2),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_snippet, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [83] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__code = 0,
  ts_external_token__front_matter_content = 1,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__code] = sym__code,
  [ts_external_token__front_matter_content] = sym__front_matter_content,
};

static const bool ts_external_scanner_states[4][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__code] = true,
    [ts_external_token__front_matter_content] = true,
  },
  [2] = {
    [ts_external_token__code] = true,
  },
  [3] = {
    [ts_external_token__front_matter_content] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_vento_external_scanner_create(void);
void tree_sitter_vento_external_scanner_destroy(void *);
bool tree_sitter_vento_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_vento_external_scanner_serialize(void *, char *);
void tree_sitter_vento_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_vento(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_vento_external_scanner_create,
      tree_sitter_vento_external_scanner_destroy,
      tree_sitter_vento_external_scanner_scan,
      tree_sitter_vento_external_scanner_serialize,
      tree_sitter_vento_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
